# Generated by Django 5.2.1 on 2025-05-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
